name: community_charts_common
version: 2.0.3

environment:
  sdk: '>=2.15.1 <4.0.0'

dependencies:
  intl: 
  collection: 
  meta: 
  vector_math: 

dev_dependencies:
  mockito: ^5.3.0
  test: ^1.22.0
