name: community_charts_common
version: 2.0.3
description: A common library for charting packages. Forked from google/charts.
repository: https://github.com/juliansteenbakker/community_charts

environment:
  sdk: '>=2.15.1 <4.0.0'

dependencies:
  intl: 
  collection: 
  meta: 
  vector_math: 

dev_dependencies:
  mockito: ^5.3.0
  test: ^1.22.0
